# Generated by Django 3.0.7 on 2020-06-30 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='discroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('key', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='roomusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=10000)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rooms.discroom')),
            ],
        ),
        migrations.CreateModel(
            name='roomadmins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=100)),
                ('adminid', models.CharField(max_length=10000)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='rooms.discroom')),
            ],
        ),
    ]
