# Generated by Django 3.0.7 on 2020-06-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discroom',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
