# Generated by Django 3.0.7 on 2020-07-03 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200703_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomusers',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='rooms.discroom'),
        ),
    ]
