# Generated by Django 3.0.7 on 2020-07-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200703_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='discroom',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
