# Generated by Django 3.0.7 on 2020-07-05 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0010_userroomslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroomslist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
