# Generated by Django 3.0.7 on 2020-06-30 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllColleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField(default=0)),
                ('location', models.CharField(default='', max_length=60)),
                ('specifiedlocation', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('acceptancerate', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserColleges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('price', models.BigIntegerField(default=0)),
                ('myrating', models.IntegerField(default=5)),
                ('location', models.CharField(default='', max_length=60)),
                ('specifiedlocation', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('acceptancerate', models.IntegerField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('permission', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercolleges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
