# Generated by Django 3.0.7 on 2020-06-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_discroom_roomadmins_roomusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomadmins',
            name='root',
        ),
        migrations.RemoveField(
            model_name='roomusers',
            name='connection',
        ),
        migrations.DeleteModel(
            name='discroom',
        ),
        migrations.DeleteModel(
            name='roomadmins',
        ),
        migrations.DeleteModel(
            name='roomusers',
        ),
    ]
